#!/bin/bash

echo "=========================================="
echo "Example Usage of Structured Inference"
echo "=========================================="
echo ""

echo "1. Generate structured training data:"
echo "--------------------------------------"
echo "uv run python scripts/generate_structured_data.py \\"
echo "  --output ./data/structured \\"
echo "  --num-samples 1000"
echo ""

echo "2. Train model with structured data:"
echo "-------------------------------------"
echo "uv run python -m src.train \\"
echo "  --use-lora \\"
echo "  --model-type qwen3 \\"
echo "  --data-path ./data/structured/train.jsonl \\"
echo "  --use-conversation-format \\"
echo "  --num-epochs 3"
echo ""

echo "3. Regular inference (HuggingFace Transformers):"
echo "-------------------------------------------------"
echo "# With LoRA adapter:"
echo "uv run python inference_structured.py \\"
echo "  --model-path ./outputs/lora \\"
echo "  --base-model 'Qwen/Qwen3-0.6B' \\"
echo "  --text 'Tim Cook announced Apple quarterly earnings.' \\"
echo "  --schema-file test_schema.json"
echo ""

echo "# With merged model:"
echo "uv run python inference_structured.py \\"
echo "  --model-path ./outputs/lora/merged \\"
echo "  --text 'Tim Cook announced Apple quarterly earnings.' \\"
echo "  --schema-file test_schema.json"
echo ""

echo "# Batch processing:"
echo "uv run python inference_structured.py \\"
echo "  --model-path ./outputs/lora/merged \\"
echo "  --input-file test_texts.txt \\"
echo "  --output-file results.json \\"
echo "  --schema-file test_schema.json"
echo ""

echo "4. vLLM inference with guided generation:"
echo "------------------------------------------"
echo "# First install vLLM:"
echo "pip install vllm"
echo ""

echo "# Run inference with schema enforcement:"
echo "uv run python inference_vllm_structured.py \\"
echo "  --model-path ./outputs/lora/merged \\"
echo "  --text 'Tim Cook announced Apple quarterly earnings.' \\"
echo "  --schema-file test_schema.json \\"
echo "  --temperature 0.1"
echo ""

echo "# Batch processing with vLLM:"
echo "uv run python inference_vllm_structured.py \\"
echo "  --model-path ./outputs/lora/merged \\"
echo "  --input-file test_texts.txt \\"
echo "  --output-file vllm_results.json \\"
echo "  --schema-file test_schema.json \\"
echo "  --batch-size 8"
echo ""

echo "5. Schema file format:"
echo "----------------------"
echo "See test_schema.json for example:"
cat test_schema.json
echo ""

echo "=========================================="
echo "Note: The quick 5-step training is just for testing."
echo "For production use, train for more epochs (e.g., 3-5)"
echo "with a larger dataset (1000+ samples)."
echo "=========================================="