model:
  model_name: "google/gemma-2b"
  max_length: 512
  load_in_4bit: false
  load_in_8bit: false
  device_map: "auto"
  trust_remote_code: true

lora:
  r: 16
  lora_alpha: 32
  lora_dropout: 0.1
  bias: "none"
  target_modules:
    - "q_proj"
    - "v_proj"
    - "k_proj"
    - "o_proj"
    - "gate_proj"
    - "up_proj"
    - "down_proj"

training:
  output_dir: "./outputs/lora"
  num_train_epochs: 3
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4
  gradient_accumulation_steps: 4
  gradient_checkpointing: true
  learning_rate: 2.0e-4
  lr_scheduler_type: "cosine"
  warmup_ratio: 0.1
  weight_decay: 0.01
  logging_steps: 10
  save_steps: 100
  eval_steps: 100
  save_total_limit: 3
  max_seq_length: 512
  packing: false
  dataset_num_proc: 4
  fp16: false
  bf16: false
  tf32: true
  optim: "adamw_torch"
  seed: 42
  remove_unused_columns: false
  report_to:
    - "tensorboard"

data:
  dataset_name: "conll2003"
  max_samples: null
  validation_split: 0.1
  seed: 42