model:
  model_name: "google/gemma-2b"
  max_length: 512
  load_in_4bit: false
  load_in_8bit: false
  device_map: "auto"
  trust_remote_code: true

training:
  output_dir: "./outputs/sft"
  num_train_epochs: 3
  per_device_train_batch_size: 2
  per_device_eval_batch_size: 2
  gradient_accumulation_steps: 8
  gradient_checkpointing: true
  learning_rate: 5.0e-5
  lr_scheduler_type: "cosine"
  warmup_ratio: 0.1
  weight_decay: 0.01
  logging_steps: 10
  save_steps: 200
  eval_steps: 200
  save_total_limit: 3
  max_seq_length: 512
  packing: false
  dataset_num_proc: 4
  fp16: false
  bf16: false
  tf32: true
  optim: "adamw_torch"
  seed: 42
  remove_unused_columns: false
  report_to:
    - "tensorboard"

data:
  dataset_name: "conll2003"
  max_samples: null
  validation_split: 0.1
  seed: 42